@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "application.domen.MainController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1068799382 { 
   	label=models
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Circle12873928[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Circle</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   size: Double [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ shapeDraw(context: GraphicsContext)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Shape12873928[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Shape</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   background: Color [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   border: Color [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   posX: Double [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   posY: Double [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ shapeDraw(context: GraphicsContext)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Square12873928[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Square</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   size: Double [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ shapeDraw(context: GraphicsContext)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Triangle12873928[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Triangle</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   size: Double [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   vertexs: Point2D[] [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- calculateVertexs(): Point2D[]</TD></TR>
<TR><TD ALIGN="LEFT" >+ shapeDraw(context: GraphicsContext)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_95766891 { 
   	label=domen
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   MainController1393361075[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MainController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   background: ColorPicker [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   border: ColorPicker [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   clearButton: Button [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   infoShape: Label [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   shape: Shape [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   sheet: Canvas [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   sizeNumber: Spinner&lt;Integer&gt; [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ clearCanvas(actionEvent: ActionEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ drawCanvas(mouseEvent: MouseEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ initialize(url: URL, resourceBundle: ResourceBundle)</TD></TR>
<TR><TD ALIGN="LEFT" >+ selectCircle(actionEvent: ActionEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ selectSquare(actionEvent: ActionEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ selectTriangle(actionEvent: ActionEvent)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
MainController1393361075 -> Shape12873928[label="shape
[0..1]"];
Shape12873928 -> Circle12873928[arrowhead=none, arrowtail=empty, dir=both];
Shape12873928 -> Square12873928[arrowhead=none, arrowtail=empty, dir=both];
Shape12873928 -> Triangle12873928[arrowhead=none, arrowtail=empty, dir=both];
    
}
@enduml